name: java-spring-cache-redis-plugin
description: This plugin aims to enable the ability to use Cache with Redis in your Java Spring Boot Application
display-name: java-spring-cache-redis-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
  - maven
  - application.yaml
about: docs/pt-br/doc.md
usage: docs/pt-br/doc.md
use-case: docs/pt-br/doc.md
implementation: docs/pt-br/doc.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
computed-inputs:
  directory: "{{directory_path | replace('.','/')}}"
  directory_test: "{{directory_test_path | replace('.','/')}}"
hooks:
  ##
  # Edit pom.xml add multiples dependencies with Spring Data Redis and Test Containers
  ##
  - type: edit
    path: pom.xml
    trigger: after-render
    changes:
      - search:
          string: "</dependencies>"
          insert-before:
            snippet: snippets/snippet-pom.xml
          when:
            not-exists-snippet: snippets/snippet-pom.xml
      - search:
          string: "</dependencies>"
          insert-before:
            snippet: snippets/snippet-pom-dependecies-test-containers-redis.xml
          when:
            not-exists: "testcontainers-redis-junit"

  ##
  # Edit application.yaml
  ##
  - type: edit
    path: src/main/resources/application.yaml
    trigger: after-render
    changes:
      - search:
          string: "spring:"
          insert-after:
            snippet: snippets/snippet-application.yaml
          when:
            not-exists-snippet: snippets/snippet-application.yaml
      - insert:
          line: -1 
          value: "\nlogging.level.org.springframework.cache: TRACE"
          when:
            not-exists: "logging.level.org.springframework.cache: TRACE"
          
  ##
  # Create or edit docker-compose.yaml
  ##
  - type: render-templates
    trigger: after-render
    path: snippets/docker-redis

  ##
  # Create path directory samples
  ##
  - type: run-script
    trigger: before-input
    script: snippets/open-pom.py
